name: Package VS Code Extension and Push VSIX

on:
  push:
    branches:
      - main  # Replace with your desired source branch

jobs:
  build-and-push-vsix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required to push to another branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install vsce globally
        run: npm install -g vsce

      - name: Package the VS Code extension
        run: vsce package

      - name: Clean up git changes before switching branches
        run: git reset --hard

      - name: Push VSIX to `vsix-artifacts` branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
      
          # 🗂 Move VSIX to temp directory first
          mkdir -p temp-vsix
          mv *.vsix temp-vsix/extension.vsix
      
          # 🌱 Create orphan branch
          git switch --orphan vsix-artifacts
      
          # 🧹 Clean all files (if any left)
          git rm -rf . || true
      
          # 🚚 Move VSIX back into working directory
          mv temp-vsix/extension.vsix .
      
          git add extension.vsix
          git commit -m "Build VSIX from ${GITHUB_SHA}"
          git push -f origin vsix-artifacts
